spring.application.name=first_project
server.port=8082
class.cr=Rahul
class.Name=CSE-A
# server.servlet.context-path=/login
# Using `com.sharma.demo.security.SecurityConfig` for role-based users.
#spring.security.user.name=katgaya
#spring.security.user.password=katgaya@123